### ISSUE TITLE
Debugger User Acceptance Testing - Bugfix Roadmap

### ISSUE THREAD

**Issue by retrobenny** [project64/project64#1476]
Please test all of the extensive features of the debugger and other functions to ensure things are working as intended,and please list any issue/s you encounter and how to reproduce them.
I hope someone can create an advanced list for crossing each problem out once it becomes resolved,of course after a list gets populated with said issues.

I will start off with my quick test of Project64 2.4.0-692-gf20dca3 .

Recompiler still runs into a breakpoint error if you attempt to set an execution breakpoint.

![image](https://user-images.githubusercontent.com/16418716/43112694-e4b83e3a-8ebc-11e8-9131-d1b865d23232.png)

1. Run Super Mario 64 (in recompiler)

2. Open the Commands window via "Breakpoints..." and navigate to 80248034 then double click it to set an execution breakpoint then go back to the game window.

3. You would normally see the proper breakpoint happen with the PC address spot for the breakpoint location but instead you will most likely encounter an error breakpoint as seen in the provided image.

**Comment by project64** [comment]
I really need a wiki to have this kind of information .. bugs are the not right place, but do not have anything really better ..

I am not sure how useful User Acceptance Testing is. Maybe it helps let other people test. I am willing to run through the tests when I am getting to a final build. But I will not be doing testing unless I know something is broken.

**Comment by theboy181** [comment]
Im confused. Did he not report something  that is broken, and included the test?

**Comment by project64** [comment]
maybe I miss read it based on the title, I probably skimmed it and expected the content to match the title. 

If it is a bug with steps to fix then I can look at fixing it

**Comment by theboy181** [comment]
When this is fixed we can see if the other issues we are seeing were caused by this. :) thanks @retrobenny

**Comment by project64** [comment]
this should https://github.com/project64/project64/commit/ba0124efa89630ccb736ebe2c3a1f98894daa018 fix the issue

**Comment by theboy181** [comment]
OH MY!!!
ill test the hell out of this! 
When can we see a bin?

**Comment by oddMLan** [comment]
https://www.pj64-emu.com/nightly-builds , no?

**Comment by project64** [comment]
it is currently building, will be up shortly

**Comment by theboy181** [comment]
2.40.693

Snowboard Kids (U)

1.) open ROM
2.) open Memory Viewer
3.) set address to 8011255C
4.) set read BP on first byte
5.) command window will open with a soft lock, and the address will be incorrect.
6.) clear BP by pressing X under "GO" click "GO" game will not show any updated frames

Note: this was only tested with recompiler/interpreter

**Comment by retrobenny** [comment]
Yeah,that is an issue if you don't already have the command window open.
Maybe there should be a breakpoint miss delay which waits for the command window to load before attempting to reach that breakpoint.

2.4.0-693-gba0124e

Super Mario 64 (U)

1. open the game
2. open Commands window
3. go to 80248020 and set an execution breakpoint on 80248028 via double clicking
4. click on the game window to activate the BP
5. successfully obtain a BP but at a not fully accurate location of 80248000
6 (last step). click go and realize that its acting like step for some reason

Notes: It survives after deleting the executiion BP and continues running the game fine,the read and write BPs are working perfectly on my first test using 0007EFB4 and 0007EFB6 for each type and those also survived after BP deletion then clicking Go.

![image](https://user-images.githubusercontent.com/16418716/43371089-7a6a5020-9350-11e8-983f-1decf730b4cd.png)

**Comment by project64** [comment]
I am trying to see why it happens, but basically the debugger is thinking you changed the PC to 0
so you get all *** at the address casuse it thinks that the PC is 0
and when you go/step it generates exceptions cuase it is executing from 0

**Comment by theboy181** [comment]
@project64 

@retrobenny reported another issue, and this one is a larger issue, I tested with the above instructions and see he is correct. PJ64 BP is bugged regarding this process. 

I also tested the latest build and the command window is populating as it should now.  THANK YOU! 

Could you please take it a few steps further? I know it would make the debugging process even more intuitive. 

Can you please add the following features

1.) Debug Windows retain their last know position in the config file, and load to that position on open. (when debugger is enabled)
2.) Command Window will return to its last position, and return to the desktop if its been minimized, while a BP is executed from the Memory Viewer.
3.) Restore the functionality of "View Memory..." from the right click context menu in the Commands Window. (right click any instruction)


I have other requests for the general GUI and Hotkeys, but I think that these two items are a good start.

Do we know if @shygoo has any plans, or requests for the future of PJ debugger? I would like to know what is next on the list, now that PJ64 debugging is almost completed for the recompiler. :)

**Comment by project64** [comment]
https://github.com/project64/project64/commit/c1200514c6c56a9ef48d0d1a9e11fb35e44561df should fix the address being wrong

**Comment by retrobenny** [comment]
I can confirm it is working upon testing the address execution BP on 80248028 again.

**Comment by theboy181** [comment]
Working now.

Odd thing though, the Commands address doesnt update when you enter a memory adress

1.) Open ROM (SM64)
2.) Open Commands Window
3.) Copy 80248020  into the address area 
![image](https://user-images.githubusercontent.com/9299743/43425053-471568de-9406-11e8-8076-1108541d0adc.png)
4.) Observe that it will not bring you to that address, even if you press ENTER
5.) Scroll down n the command window, then enter address
6.) Observe that this now works

**Comment by retrobenny** [comment]
Strange,its working on my end just after opening the commands window.
Did you disable the "pause on focus lost" setting?

I leave that enabled myself.

Will now likely test recompiler debugger on Conker in numerous conditions to see if it holds up.
As Conker is the worst case for slowdown on Interpreter,it will be more tolerable with debugger on recompiler,hope it turns out to work fairly stable.

@project64 

A few extra details:

1. Perhaps please make hardware addresses (A4000000 for example) work in memory viewer without crashing things if you don't mind trying to fix that and maybe also make it work for addresses like B0xxyyyy in Zelda Ocarina of Time which seems to store actor data and other stuff that one could mess with if it didn't cause crashing or (I forgot) whatever it does.
It turns out that is the rom_data itself which I guess explains the reason for it to respond strongly at attempts of messing with it.

I still wonder how Game Genie even works on older 2D systems (on actual consoles) since it modifies the game data itself,as you can use decrypted Game Genie codes to edit the games directly in a hex editor to make permanent in-built cheats in exception to dealing with the checksum stuff.

**Comment by retrobenny** [comment]
Forgot that there is another issue still.

Whenever you try to step through a JAL,it will not let you continue through it until clicking the game windows.
This is a REALLY frustrating problem.

**Comment by retrobenny** [comment]
Darn! Conker now freezes at the beginning of the intro cut-scene (a few seconds into the N logo chainsaw scene) with my settings.

![image](https://user-images.githubusercontent.com/16418716/43428371-909569d8-9423-11e8-9636-5255d4d7c046.png)

Apply those settings,then open the game (debugger enabled on my end still) and wait for it to load after a bit.

Once reaching the start of the scene,it should just freeze with no errors appearing.

**Comment by retrobenny** [comment]
More about the frustrating JAL and JR stepping issue.

Example to mimic;

1. Run Super Mario 64 and wait until the head appears.

2a. Set an execution BP on 80248028 and step through the nearby JAL and it might prevent you from pressing step when attempting to jump to the address it is assigned to.
2b. If it does not get stuck then keep stepping through the address it ends up on until reaching 80277F00 then you are close to the a JR.

3 (2b). Step through the JR and it should no longer allow you to step further until clicking back into the game window.

Note: May need "pause if focus lost" enabled in order to have this issue.

**Comment by theboy181** [comment]
@project64 found a bug 

1.) Set PJ64 to recompiler
2.) Load RR64 - Ridge Racer 64 (U)
3.) Start a race
4.) In command window NOP 80001A18
5.) Observe game speed is not impacted ( Nop should make the game 60fps)
6.) double click 80001A18 in the command window, then clear BP and press GO
7.) Observe game is now running at 60fps.
8.) do steps 1-4 using interpreter.
9.) Observe NOP changes game to 60fps immediately.

**Comment by retrobenny** [comment]
I can confirm this,but its not exactly a bug,but a limitation of recompiler itself.
That can be fixed by doing something similar or exactly how Mupen64Plus does as I mentioned in an old issue post #851  that never got any progression unfortunately.

**Comment by Ecksters** [comment]
https://github.com/project64/project64/issues/1452

**Comment by project64** [comment]
main issue has been fixed, if there is other issues to be fixed open new issues for just one isse

**Comment by cxd4** [comment]
Yeah what do you think this is, the cheats section of PJ64 Forums or something.

(Heh, sorry.)
