### ISSUE TITLE
PJGlide64 memory leaks

### ISSUE THREAD

**Issue by cxd4** [project64/project64#51]
I will send a pull request shortly to enable Glide64's debugger logging feature when building as Debug.

In the meantime, running the debug build of PJGlide64, I get reports of memory leaks with weird C++.

One is Config.cpp line 1116:
`hostWindow = new wxWindow();`
The other is Config.cpp line  1291:
`hostWindow = new wxWindow();`

Evidently the same thing--the only difference, one is in DllConfig, the other in DllAbout.  If you run this plugin in debug mode and close out of Project64 with a normal exit, a debug message should tell you a memory leak occurred because you tried to configure the plugin or click the About button.

**Comment by project64** [comment]
so hostWindow is allocated but never deleted.

**Comment by cxd4** [comment]
Sounds sensible.  I like `malloc` and `free`.

**Comment by cxd4** [comment]
I tried doing a consecutive pull request for this.

It partly worked, partly didn't.  I think the change itself had a problem:  `delete hostWindow;` like you said, at least the end of the function, solved the memory leak for DllConfig...but introduces crashing with DllAbout if you click About multiple times.  So I guess I can only fix one of them myself, without screwing around with C++ experiences at least.

**Comment by Frank-74** [comment]
I've managed to get rid of those 2 memory leaks with this https://github.com/Frank-74/project64/commit/23833f2b824beea4c4c767430ed47041636cac89.
But still have one that happens on both.

>>Order, Source File, Line Number, Mem Size
4332,Unknown, 0, 64

**Comment by Frank-74** [comment]
The remaining leak is to do with loading the settings.  I'm tracking it down.......nearly there.

**Comment by cxd4** [comment]
Neat.  Think I remember trying to add those `delete` lines in something like the way you did, though then I kept having crashes anytime I did About/Config more than one time in succession.  I'm sure that's mostly because I tried to do it and don't know anything about allocation in C++.  But I pulled from your branch and that seems to work just fine.

Guess I leave the issue open for that last one you mentioned.

**Comment by Frank-74** [comment]
Since yesterday, the remaining leak has reduced to 32 in size.

I found out the leak doesn't happen if you select Glide debug in the system plugins, and make the game use system plugins.  So its probably in Plugin Class.

And today clicking about twice causes an exception.  That never happened yesterday.

**Comment by cxd4** [comment]
I thought I remembered it doing that.  When I added the `delete` for DllAbout, then sometimes clicking About twice caused the exception.  So it's like, almost as if Glide64 is purposely relying on memory leaks to keep the resource open and re-usable, never deleted so it never crashes or something?!  IDK.

**Comment by Frank-74** [comment]
Its all fixed now with this. https://github.com/Frank-74/project64/commit/30039150ec0865a1c71fde552dc5f2d157e607cb

No more crashes, no more memory leaks.

**Comment by cxd4** [comment]
I see what you mean.  Yeah the config/about seems to work about perfectly now, but there is that hard-to-trace memory leak remaining.  I'm inclined to close the issue, but I remember I just tried sending this build to Lithium64 to test.  He also noticed the memory leak from trying to use the plugin.  So I guess technically this is still an issue in the real world due to that last, mysterious leak.

**Comment by cxd4** [comment]
Haha...is this still an issue?  I can barely even remember filing this.

Well IMO it's not Project64-related; it's plugin-related.  All these plugin issues may as well be consolidated into one issue for splitting the components away from the core.
