### ISSUE TITLE
Donkey Kong 64 - Bone Displacement

### ISSUE THREAD

**Issue by Isotarge** [project64/project64#791]
I'm reporting this long standing issue on behalf of the DK64 RTA & TAS communities.

I have completed a thorough technical analysis of the symptoms [here](https://docs.google.com/document/d/15XNghhrc-thXJpbKzWWuHXl-NXdzcaDLEf7poFVruh8)
Savestates to reproduce the issue are available [here](https://www.mediafire.com/folder/x5u53bpu42cex/Bone_Displacement_States)

Let's squish this bug!

**Comment by cxd4** [comment]
Neat and very descriptive.

I don't know if this affects anything at all about the research you wrote down and concluded, but as I skimmed through your analysis paper it says:

> The second type of displacement is fairly simple, the core correctly processes most fields of the array, but sets only the position fields to -32768 or 0xFFFF.

I was assuming if the memory loads directly in the standard R4300 operations, that you may have meant 0x8000 instead of 0xFFFF.

**Comment by Isotarge** [comment]
Thanks for the heads up, will look into the 0x8000/0xFFFF confusion.

**Comment by oddMLan** [comment]
Have you tried using Fixed Audio Timing with AI Counter Per Byte set to 0? With these options the timing gets significantly improved

![ai](https://cloud.githubusercontent.com/assets/7278372/11516038/574edb7a-983e-11e5-923f-8dd28a6b7276.png)

**Comment by mudlord** [comment]
Could be core timing indeed. 
Research is needed to find out proper COUNT register calculation without having to go the route of CEN64 and its overkill emulating everything.

**Comment by weinerschnitzel** [comment]
COUNT accuracy should fix this issue.

@LegendOfDragoon has a 1964 1.1 fork that reintroduces bone displacement at the cost of timing more like PJ64. The changes in r4300i_COP0_mtc0() could be diffed against vanilla 1964 1.1 and maybe a solution can be derived that will work for other emulators. I have yet to do my own experiments, but I thought I'd share anyway.

https://github.com/LegendOfDragoon/1964-X/blob/7374fb0e5f175ecc2f2acfa089d0814bc7d99ae1/src/core/R4300i.cpp#L1640

**Comment by Frank-74** [comment]
I don't seem to be getting this issue anymore.

I used to notice it on the demo's before pressing start.  Now I don't get it.

Can someone confirm if this has been fixed by accident?

**Comment by oddMLan** [comment]
Hm... that's a though one.
Can you compile the latest build for me?

**Comment by Frank-74** [comment]
@oddMLan 
https://dl.dropboxusercontent.com/u/9498358/n64/Project64.zip

I update that link everytime I build fresh from the master zip.

**Comment by Isotarge** [comment]
Sadly it's still an issue, I just reproduced it (including an origin warp) on the build you linked w/default settings using the tree between the warp ring and K. Lumsy in DK Isles overworld

**Comment by Frank-74** [comment]
@Isotarge 
Shame.  I used to see it on the rolling demo through the tunnels, the arms or whatever stretched across the screen horizontally.  But now I'm not getting it on the rolling demo.

Thanks for testing anyway.

**Comment by oddMLan** [comment]
![glide64_donkey_kong_64_02](https://cloud.githubusercontent.com/assets/7278372/17003740/273d94b8-4e86-11e6-9f26-9a2bd75d7799.png)

Unfortunately it is still very much reproducible.

**Comment by Frank-74** [comment]
@oddMLan 
Can you try this build?  Use the default settings.

https://dl.dropboxusercontent.com/u/9498358/n64/Project64%202.3-242%2B.zip

I've changed the timing a bit (only for (U) 60 VI's games).  Also changed the Fixed Audio options to a drop list, dynamic is same as Fixed Audio on and AI=0.  Dynamic also calculates the AI value and puts it in the cfg when the game is running.  So you've got the calculated value to work from if you need or want to change it when Fixed Audio Timing is set to On.

I've played from the beginning, visited cranky, done the training, left the area, swam across to the island.  No sign of bone displacement yet.

**Comment by oddMLan** [comment]
I still get the same problem in the pictures I posted.

**Comment by Isotarge** [comment]
^ Same here, it happened by Cranky's Lab in the Training Grounds on the new build with default settings

**Comment by Isotarge** [comment]
I have been working on this a lot lately using BizHawk's memory r/w/x callbacks to figure out more about the loop that writes bone positions. This research led to a second hacky fix for this issue that I discovered today, it still writes to RDRAM so it's not ideal but at least it doesn't lose all audio this time. See the heading "Hacky Fix 2" in the document linked in the OP for more information.

**Comment by AmbientMalice** [comment]
So this can be closed now, perhaps?

**Comment by LegendOfDragoon** [comment]
without using save states, how can I reproduce this issue? I don't seem to see it and im not using the hack that makes it go away.

**Comment by Frank-74** [comment]
@LegendOfDragoon 
Certain you removed, "Cheat0=80619632 0000 // Polygon Tearing Fix", from the RDB?

**Comment by LegendOfDragoon** [comment]
I use my own RDB, because I disagree with default settings. I don't really play DK64, so I never even tried the cheat out.

>The most consistent place for reproducing it, is outside Cranky's Lab.

So i should be able to see it by  just running/jumping around? I tried my fork of 1964 as well. I feel that maybe it's because idk how to reproduce it.

**Comment by theboy181** [comment]
@Isotarge can you see if this is still an issue in latest PJ? can't reproduce the bones issue.

**Comment by LegendOfDragoon** [comment]
@theboy181 do you have the cheat enabled?

**Comment by Isotarge** [comment]
It's still an issue in the latest official build from the website, 2.3.2.202 as the stock RDB does not contain the fix, and a fix has not been applied on the emulator side. A screenshot is attached as proof.
![bone displacement pj64 latest](https://user-images.githubusercontent.com/6367891/30360133-b66f8c6a-988e-11e7-8059-b72aa6bc5cbf.png)
If you can link me a later build to test I will happily do so but surely we're not far away from a new release with the RDRAM based fix built into the stock RDB?

**Comment by Isotarge** [comment]
@theboy181 Has linked me a build with the version number: 2.4.0.458. I removed the RDRAM based fix from the RDB that came from it and was unable to reproduce the issue.

**Comment by LegendOfDragoon** [comment]
So I was right then :smile: . Thanks for the feedback @Isotarge. I think we should remove the hack then @project64 .

**Comment by project64** [comment]
yes sounds like the rdb changes can be removed, I will add it in to my next lot of commits

**Comment by project64** [comment]
ok removed in v2.4.0-480-g0e508eb double check if you can reproduce it, otherwise I guess we can close this issue

**Comment by Isotarge** [comment]
I have double checked and still cannot reproduce the issue so I'm more than happy to close this. I just want to say a big thank you to everybody who helped out during this process!
